language: cpp
compiler:
    -clang
    -gcc

#taken from https://github.com/travis-ci/travis-ci/issues/4631
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

script:
   - mkdir build
   - cd build
   - cmake .. && make